[tool.poetry]
name = "rag-service"
version = "0.1.0"
description = "Service that vectorizes your document assets and provides RAG capability."
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
concurrent-log-handler = "^0.9.24"
fastapi = ">= 0.97.0, < 1.0.0"
langchain = "0.0.323"
sqlmodel = ">= 0.0.8, < 1.0.0"
starlette = ">= 0.27.0, < 0.28.0"
torch = "^2.0.1"
uvicorn = ">= 0.22.0, < 1.0.0"
elasticsearch = "^8.10.0"
sseclient = "0.0.27"
slowapi = "^0.1.8"
psycopg2-binary = "^2.9.9"
urllib3 = "< 2.0.0"

[tool.poetry.extras]
pgsql = ["psycopg2"]

[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[tool.poetry.scripts]
rag_app = 'rag_service.rag_app.app:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
