# 日志解析配置主文件
# 日志解析方法，可选值：base、log_detection_base_on_keywords、log_detection_base_on_clustering、log_detection_base_on_llm
LOG_PARSE_METHOD = "log_detection_base_on_llm"

# SQLite数据库文件路径
SQL_LITE_DB_PATH = "log_detection_multi_process.db"

# Embedding模型配置
[EMBEDDING_MODEL]
EMBEDDING_PROVIDER = "openai"
EMBEDDING_END_POINT = "https://api.siliconflow.cn/v1/embeddings"
EMBEDDING_API_KEY = ""
EMBEDDING_MODEL_NAME = "BAAI/bge-m3"
EMBEDDING_BATCH_SIZE = 16

# LLM模型配置
[LLM_MODEL]
LLM_PROVIDER = "openai"
LLM_END_POINT = "https://dashscope.aliyuncs.com/compatible-mode/v1"
LLM_API_KEY = ""
LLM_MODEL_NAME = "qwen3-max"
LLM_MAX_TOKENS = 32000
LLM_BATCH_SIZE = 32

# 服务运行配置
[RUN_CONFIG]
RUN_HOST = "0.0.0.0"
RUN_PORT = 12144

# OCR配置
[OCR_CONFIG]
OCR_METHOD = "offline" # 可选值：offline、online
OCR_API_URL = ""

# 日志解析特征配置
[LOG_PARSE_CONFIG]
# 要加载的日志类型，留空表示加载所有类型
# 可用类型：dmesg、kdump、ftrace、bash、python、java、go、javascript、c、cpp、unknown
LOG_TYPES_TO_LOAD = []