apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: euler-copilot
spec:
  type: ClusterIP #需暴露端口请改为NodePort
  selector:
    app: rag
  ports:
    - port: 8005
      targetPort: 8005
      # nodePort: 30008
    - port: 3000
      targetPort: 3000
      # nodePort: 30009
